jobs:

- job: 'SAST_PipelineScan'
  displayName: 'SAST - Pipeline Scan'
  dependsOn: Build

  steps:

  - script: echo '[INFO] Starting Veracode SAST - Pipeline Scan'

- job: 'SCA_ABS'
  displayName: 'SCA - Agent-Based Scan'
  dependsOn: Build

  steps:

  - script: echo '[INFO] Starting Veracode SCA - Agent-Based Scan'

- job: 'ContainerSecurity'
  displayName: 'Container/IaC Scan'
  dependsOn: Build

  steps:

  - script: echo '[INFO] Starting Veracode Container/IaC Scan'