jobs:

- job: 'FeatureXBranch_BasePipeline'
  displayName: 'FeatureX Branch - Base Pipeline'
  steps:
    - script: '[INFO] Starting Pipeline Execution...'
    - script: '[INFO] Branch - featureX'

- job: 'SAST_PipelineScan'
  displayName: 'Veracode SAST - Pipeline Scan'
  dependsOn: FeatureXBranch_BasePipeline
  steps:
  - script: echo '[INFO] Starting Veracode SAST - Pipeline Scan'

- job: 'SCA_ABS'
  displayName: 'Veracode SCA - Agent-Based Scan'
  dependsOn: FeatureXBranch_BasePipeline
  steps:
  - script: echo '[INFO] Starting Veracode SCA - Agent-Based Scan'

- job: 'ContainerSecurity'
  displayName: 'Veracode Container/IaC Scan'
  dependsOn: FeatureXBranch_BasePipeline
  steps:
  - script: echo '[INFO] Starting Veracode Container/IaC Scan'