name: Veracode SCA

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  SoftwareCompositionAnalysis:
    runs-on: ubuntu-latest
    name: Scan repository with Veracode SCA (ABS)

    steps:
        # Runs Veracode SCA (ABS)
        # This example is running a Org-Level Agent. Env variable SRCCLR_WORKSPACE_SLUG sets the workspace to upload results
        - name: VERACODE SCA - AGENT BASED SCAN
          env:
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_TOKEN }}
            SRCCLR_WORKSPACE_SLUG: 'YEEudonE'
          if: ${{ success() }}
          uses: veracode/veracode-sca@v2.1.9
          with:
            create-issues: false
            url: ${{ inputs.repo_url }}
            path: ./app
            quick: true
            debug: true