name: Veracode Policy Scan

on:
  workflow_call:
    inputs:
      VERACODE_APP_PROFILE_NAME:
        required: true
        type: string

jobs:
  PolicyScan:
    runs-on: ubuntu-latest
    steps:

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - name: Checking Out Code Repo
          uses: actions/checkout@v2

        #Gets the artifact
        - name: Downloading artifact
          uses: actions/download-artifact@v3
          with:
            name: MyBuiltArtifact

        # Runs Veracode SAST Scan
        - name: VERACODE SAST - POLICY SCAN
          if: ${{ success() }}
          uses: veracode/veracode-uploadandscan-action@0.2.6 
          with:
            appname: ${{ inputs.VERACODE_APP_PROFILE_NAME }}
            createprofile: false
            filepath: './app/target/verademo.war'
            vid: '${{ SECRETS.VID }}'
            vkey: '${{ SECRETS.VKEY }}'
            version: '${{ github.run_id }}'
            deleteincompletescan: 2

        # Verify SAST results to control workflow 
        - name: Validating SAST Scan Results
          if: ${{ success() }}
          run: |
            ls -all
            chmod -R 777 ./shell_scripts
            echo '======================================================='
            echo 'VALIDATING VERACODE SAST RESULTS...'
            echo '======================================================='
            ./shell_scripts/veracode-scan-results.sh ${{ SECRETS.VID }} ${{ SECRETS.VKEY }} ${{ inputs.VERACODE_APP_PROFILE_NAME }}

