name: Veracode SCA

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      head_ref:
        required: true
        type: string

jobs:
  SoftwareCompositionAnalysis:
    runs-on: ubuntu-latest
    steps:

        #Gets the artifact
        - name: Downloading artifact
          uses: actions/download-artifact@v3
          with:
            name: MyBuiltArtifact

        # Runs Veracode Sandbox Scan
        - name: VERACODE SCA - AGENT BASED SCAN
          if: ${{ success() }}
          run: |
            echo 'Prueba del Repo'
            echo ${{ repo_url }}
            echo ${{ hed_ref }}
            ls -la
