name: Veracode SCA

on:
  workflow_call:
    inputs:
      SRCCLR_WORKSPACE_SLUG:
        required: true
        type: string
      SRCCLR_SCAN_DIR:
        required: true
        type: string

jobs:
  SoftwareCompositionAnalysis:
    runs-on: ubuntu-latest
    name: SoftwareCompositionAnalysis

    steps:
        # Repo Checkout
        - uses: actions/checkout@v4.1.1
          with:
            repository: ${{ github.event.client_payload.repository.full_name }}
            ref: ${{ github.event.client_payload.sha }}

        - run: |
            ls -la

        # Runs Veracode SCA (ABS)
        # This example is running a Org-Level Agent. Env variable SRCCLR_WORKSPACE_SLUG sets the workspace to upload results.
        - name: VERACODE SCA - AGENT BASED SCAN
          env:
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_TOKEN }}
            SRCCLR_WORKSPACE_SLUG: ${{ inputs.SRCCLR_WORKSPACE_SLUG }}
          if: ${{ success() }}
          uses: veracode/veracode-sca@v2.1.9
          with:
            create-issues: false
            debug: false
            path: ${{ inputs.SRCCLR_SCAN_DIR }}
