name: Veracode Policy Scan
   
on:
  workflow_call:
    inputs:
      VERACODE_APP_PROFILE_NAME:
        required: true
        type: string

jobs:
  PolicyScan:
    runs-on: ubuntu-latest
    steps:

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - name: Checking Out Code Repo
          uses: actions/checkout@v2

        #Gets the artifact
        - name: Downloading artifact
          uses: actions/download-artifact@v4
          with:
            name: MyBuiltArtifact

        # Runs Veracode SAST Scan
        - name: VERACODE SAST - POLICY SCAN
          if: ${{ success() }}
          uses: veracode/veracode-uploadandscan-action@0.2.6 
          with:
            appname: ${{ inputs.VERACODE_APP_PROFILE_NAME }}
            createprofile: true
            filepath: './app/target/verademo.war'
            vid: '${{ SECRETS.VID }}'
            vkey: '${{ SECRETS.VKEY }}'
            version: '${{ github.run_id }}'
            deleteincompletescan: 2
