name: Veracode Sandbox Scan

on:
  workflow_call:
    inputs:
      VERACODE_APP_PROFILE_NAME:
        required: true
        type: string
      VERACODE_SANDBOX_NAME:
        required: true
        type: string

jobs:
  SandboxScan:
    runs-on: ubuntu-latest
    steps:

        #Gets the artifact
        - name: Downloading artifact
          uses: actions/download-artifact@v4
          with:
            name: MyBuiltArtifact

        # Runs Veracode Sandbox Scan
        - name: VERACODE SAST - SANDBOX SCAN
          if: ${{ success() }}
          uses: veracode/veracode-uploadandscan-action@0.2.6 
          with:
            appname: ${{ inputs.VERACODE_APP_PROFILE_NAME }}
            createprofile: true
            filepath: './app/target/verademo.war'
            vid: '${{ SECRETS.VID }}'
            vkey: '${{ SECRETS.VKEY }}'
            createsandbox: true
            sandboxname: ${{ inputs.VERACODE_SANDBOX_NAME }}
            version: '${{ github.run_id }}'
            deleteincompletescan: 2
